---
title: "Elexon BMU capacity factors check"
format: html
---

```{r include=FALSE}
require(tidyverse)
require(kableExtra)
require(parallel)
require(dplyr)
require(scales)
require(ggsci)

require(jsonlite)
require(httr)

require(data.table)
require(sf)
library(rnaturalearth)
library(rnaturalearthdata)

require(plotly)
require(ggthemes)

require(ggrepel)
```

## Data paths

```{r}
path <- "~/Documents/elexon"
```

```{r}
source("aux_funct.R")
```

```{r}
year_seq <- seq(2019,2025,1)

bmu_df <- lapply(year_seq, function(x){
  file_path <- file.path(path, "data_by_year", paste0("wind_gen_bmu_", x, ".csv.gz"))
  fread(file_path)
}) %>% bind_rows()
```



```{r}
ref_catalog_2025 <- fread(
  file.path("data/ref_catalog_wind_2025.csv.gz")) 
top_wind_bmus <- wind.bmus %>% 
  filter(generationCapacity>0) %>% 
  select(elexonBmUnit, leadPartyName, bmUnitName, generationCapacity) %>% 
  unique() %>% 
  arrange(desc(generationCapacity)) %>%
  mutate(
    cum_capacity = cumsum(generationCapacity),
    cum_cap_perc = cum_capacity / sum(generationCapacity)
    ) 
```


```{r}
top_wind_bmus %>% 
  arrange(desc(generationCapacity)) %>% 
  head(50) %>% 
  mutate(
    short_name = gsub("WF|Wind|Wind farm|Windfarm|Offshore","",bmUnitName)
  ) %>% 
  ggplot()+
  geom_bar(
    aes(x = reorder(short_name, -generationCapacity), 
    y = generationCapacity), 
    stat = "identity", 
    position = "dodge",
    fill = "darkblue"
    )+
  theme(
    axis.text.x = element_text(angle = 90)
  )+ labs(x  = "", y = "Capacity MW")
```


```{r}
top_gen_bmus <- bmu_df %>% 
  mutate(
    year = year(halfHourEndTime),
    quarter = paste0(year,"Q",quarter(halfHourEndTime))
    ) %>% 
  filter(bmUnit %in% top_wind_bmus$elexonBmUnit) %>% 
  group_by(
    year,
    bmUnit
  ) %>% 
  arrange(halfHourEndTime) %>%
  mutate(quantity = quantity + lag(quantity)) %>%
  filter(minute(halfHourEndTime) == 0) %>%
  summarise(
    quantity = sum(quantity, na.rm = TRUE),
    n_hours = n_distinct(halfHourEndTime)
  ) %>% 
  filter(
    quantity>0,
    n_hours > max(n_hours)*0.8) %>% 
  left_join(
    top_wind_bmus %>% select(elexonBmUnit, bmUnitName, generationCapacity) ,
    by = c("bmUnit" = "elexonBmUnit") 
  ) %>% 
  left_join(
    ref_catalog_2025 %>% select(bmUnit, tech_typ),
    by = "bmUnit"
  ) %>% 
  mutate(
    cap_factor = quantity / generationCapacity / n_hours,
    short_name = gsub("WF|Wind farm|Windfarm|Offshore","",bmUnitName)
  )
```

```{r}
# Compute means per year and technology type
means_df <- top_gen_bmus %>%
  group_by(year, tech_typ) %>%
  summarise(mean_cf = mean(cap_factor, na.rm = TRUE), .groups = "drop")

# Identify outliers per year and tech_typ
outliers_df <- top_gen_bmus %>%
  group_by(year, tech_typ) %>%
  mutate(
    Q1 = quantile(cap_factor, 0.25, na.rm = TRUE),
    Q3 = quantile(cap_factor, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    is_outlier = cap_factor < (Q1 - 1.5 * IQR) | cap_factor > (Q3 + 1.5 * IQR)
  ) %>%
  filter(is_outlier) %>%
  ungroup()

top_gen_bmus %>% 
  ggplot(aes(x = year, y = cap_factor, group = year, fill = tech_typ))+
  geom_boxplot()+
  facet_wrap(~tech_typ)+
   geom_text(
    data = means_df,
    aes(x = year, y = mean_cf, 
    label = paste0("bar(c) == ", sprintf("%.2f", mean_cf))
    ),  
    vjust = -0.7,     # move label slightly above the mean
    size = 2,         # text size
    color = "white",
    parse = TRUE
  ) +
  # outlier labels
  geom_text_repel(
    data = outliers_df,
    aes(x = year, y = cap_factor, label = short_name),
    size = 1.5,
    color = "black",
    max.overlaps = 20,     # adjust to allow more/less overlap
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey50"
  ) +
  scale_fill_manual(values = mypalette)+
  theme(legend.position = "none")+
  labs(x = "year", y = "Capacity factor")

ggsave(
    filename = "fig/capacity_factor0.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```


```{r}
top_gen_bmus_q <- bmu_df %>% 
  mutate(
    year = year(halfHourEndTime),
    quarter = paste0(year,"Q",quarter(halfHourEndTime))
    ) %>% 
  filter(bmUnit %in% top_wind_bmus$elexonBmUnit) %>% 
  group_by(
    quarter,
    bmUnit
  ) %>% 
  arrange(halfHourEndTime) %>%
  mutate(quantity = quantity + lag(quantity)) %>%
  filter(minute(halfHourEndTime) == 0) %>%
  summarise(
    quantity = sum(quantity, na.rm = TRUE),
    n_hours = n_distinct(halfHourEndTime)
  ) %>% 
  filter(
    quantity>0,
    n_hours > max(n_hours)*0.8) %>% 
  left_join(
    top_wind_bmus %>% select(elexonBmUnit, bmUnitName, generationCapacity) ,
    by = c("bmUnit" = "elexonBmUnit") 
  ) %>% 
  left_join(
    ref_catalog_2025 %>% select(bmUnit, tech_typ),
    by = "bmUnit"
  ) %>% 
  mutate(
    cap_factor = quantity / generationCapacity / n_hours,
    short_name = gsub("WF|Wind farm|Windfarm|Offshore","",bmUnitName)
  )
# Compute means per year and technology type
means_df <- top_gen_bmus_q %>%
  group_by(quarter, tech_typ) %>%
  summarise(mean_cf = mean(cap_factor, na.rm = TRUE), .groups = "drop")

# Identify outliers per year and tech_typ
outliers_df <- top_gen_bmus_q %>%
  group_by(quarter, tech_typ) %>%
  mutate(
    Q1 = quantile(cap_factor, 0.25, na.rm = TRUE),
    Q3 = quantile(cap_factor, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    is_outlier = cap_factor < (Q1 - 1.5 * IQR) | cap_factor > (Q3 + 1.5 * IQR)
  ) %>%
  filter(is_outlier) %>%
  ungroup()


```

```{r}
top_gen_bmus_q %>% 
  group_by(tech_typ,quarter) %>% 
  summarise(cap_factor = mean(cap_factor)) %>% 
  ggplot(aes(x = quarter, y = cap_factor, group = 1, col = tech_typ))+
  geom_line()+
  facet_wrap(~tech_typ, nrow = 2)+
  #  geom_text(
  #   data = means_df,
  #   aes(x = quarter, y = mean_cf, 
  #   label = paste0("bar(c) == ", sprintf("%.2f", mean_cf))
  #   ),  
  #   vjust = -0.7,     # move label slightly above the mean
  #   size = 2,         # text size
  #   color = "white",
  #   parse = TRUE
  # ) +
  # outlier labels
  # geom_text_repel(
  #   data = outliers_df,
  #   aes(x = quarter, y = cap_factor, label = short_name),
  #   size = 1.5,
  #   color = "black",
  #   max.overlaps = 20,     # adjust to allow more/less overlap
  #   box.padding = 0.3,
  #   point.padding = 0.2,
  #   segment.color = "grey50"
  # ) +
  scale_color_manual(values = mypalette)+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )+
  labs(x = "Quarter", y = "Capacity factor", col = "")

ggsave(
    filename = "fig/capacity_factor_q0.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```

## alternative capacity by BMU 

```{r}

power_park <- readxl::read_xlsx("data/power-park-modules.xlsx", sheet = 1, n_max = 252) %>% 
  rename(
    elexonBmUnit = `Settlement BMU name`,
    capacity_alt = `BMU or Large Reg Cap only`
  )
names(power_park) <- tolower(gsub(" ", "_", names(power_park)))
wind.bmus.alt <- wind.bmus %>% 
  left_join(
    power_park %>% select(elexonbmunit,capacity_alt),
    by = c("elexonBmUnit"="elexonbmunit")
  ) %>% 
  mutate(
    diff_cap = abs(generationCapacity-capacity_alt),
    capacity = case_when(
      is.na(capacity_alt) ~ generationCapacity,
      capacity_alt <= 0 ~ generationCapacity,
      diff_cap > generationCapacity * 0.1 ~ capacity_alt,
      TRUE ~ generationCapacity
    )
  )
write.csv(wind.bmus.alt, "data/wind_bmu_alt.csv", row.names = FALSE)
p_cap <- wind.bmus.alt %>% 
  ggplot()+
  geom_point(
    aes(
      generationCapacity,
      capacity, 
      text = paste("BM Unit:", elexonBmUnit,
                 "<br>Gen Cap:", generationCapacity,
                 "<br>Alt Cap:", capacity)))
ggplotly(p_cap, tooltip = "text")
```

## Curtailment 
```{r}
year_seq <- seq(2019,2025,1)

curt_df <- lapply(year_seq, function(x){
  file_path <- file.path(path, "data_by_year", paste0("wind_curt_bmu_", x, ".csv.gz"))
  fread(file_path)
}) %>% bind_rows() %>% 
  filter(dataType == "Tagged")

```


```{r}
# 2530106 : x
# Row 6245 of `y`

bmu_df %>% 
  mutate(settlementDate = as.Date(settlementDate)) %>% 
  slice(2530106)

curt_df %>% 
  mutate(settlementDate = as.Date(settlementDate)) %>% 
  filter(settlementDate == "2020-01-01",settlementPeriod==1)

curt_df %>% 
  mutate(settlementDate = as.Date(settlementDate)) %>% 
  slice(6245)

bmu_df %>% 
  mutate(settlementDate = as.Date(settlementDate)) %>% 
  filter(
    bmUnit == "T_ARCHW-1",
    settlementDate == "2019-02-14",settlementPeriod==3)

```

### Check for 1 day 1 location

```{r}
# confirmed curtailment day
c_day <- "2025-02-19"

bmu_code <- c("T_SGRWO-2")

code <- "DBAWO"

gen_frag <- bmu_df %>% 
  filter(
    settlementDate %in% c_day,
    grepl(code, bmUnit)
    # bmUnit %in% bmu_code
  )

curt_frag <- curt_df %>% 
  filter(
    settlementDate %in% c_day,
    grepl(code, bmUnit)
  ) %>% 
    mutate(
      halfHourEndTime = startTime + minutes(30)
    )

gen_adj <- gen_frag %>% 
  left_join(
    curt_frag %>% select(
      settlementPeriod, bmUnit, totalVolumeAccepted
    ),
    by = c("settlementPeriod","bmUnit")
  ) %>% 
  mutate(totalVolumeAccepted = replace_na(totalVolumeAccepted, 0)) %>%
  mutate(
    potential = quantity - totalVolumeAccepted
  ) %>% 
  left_join(
    wind.bmus.alt %>% select(elexonBmUnit,bmUnitName, capacity),
    by = c("bmUnit"="elexonBmUnit")
  ) 
  

```

```{r}

gen_adj %>%
  select(halfHourEndTime, bmUnit, quantity, totalVolumeAccepted, capacity) %>%
  mutate(
    quantity = quantity *2,
    curtailment = -totalVolumeAccepted*2) %>%
  pivot_longer(cols = c(quantity, curtailment),
               names_to = "type",
               values_to = "value") %>% 
  ggplot( aes(x = halfHourEndTime, y = value, fill = type)) +
  geom_area(position = "stack") +
  geom_hline(aes(yintercept = capacity)) +
  facet_wrap(~bmUnit) +
  scale_fill_aaas(name = "Type",
                  ) +
  theme_minimal()
```


### Combine with generation

```{r}
gen_adj <- bmu_df %>% 
  select(settlementDate,settlementPeriod,bmUnit,halfHourEndTime,quantity) %>% 
  unique() %>% 
  mutate(settlementDate = as.Date(settlementDate)) %>% 
  # head(30) %>% 
  left_join(
    curt_df %>% 
      select(settlementDate,settlementPeriod,bmUnit,totalVolumeAccepted) %>% 
      unique() %>% 
      mutate(settlementDate = as.Date(settlementDate)),
    by = c("settlementDate","settlementPeriod","bmUnit")
    ) %>% 
  mutate(
    curtailment = replace_na(-totalVolumeAccepted, 0),
    potential = quantity + curtailment) %>% 
  left_join(
    wind.bmus.alt %>% 
      select(elexonBmUnit,bmUnitName, capacity) %>% 
      unique(),
    by = c("bmUnit"="elexonBmUnit")
  ) %>% 
  filter(
    capacity > 0,
    potential > 0
  ) %>% 
  mutate(
    cap_factor = ifelse(capacity >0 , potential/capacity)
  )

arrow::write_parquet(
  gen_adj,
  file.path(path,"gen_adj.parquet"))
```

```{r}
pot_summary <- gen_adj %>% 
  filter(
    halfHourEndTime >= "2024-01-01",
    halfHourEndTime <= "2024-12-31",
  ) %>% 
  group_by(bmUnit) %>% 
  summarise(
    across(c(quantity, curtailment, potential), sum),
    capacity = max(capacity),
    n_hours = n_distinct(halfHourEndTime)
  ) %>% 
  left_join(
    ref_catalog_2025 %>% select(bmUnit, tech_typ),
    by = "bmUnit"
  ) %>% 
    mutate(
      cf = quantity / capacity / n_hours *2,
      pf = potential / capacity / n_hours *2
    )
  
pot_summary %>% 
  write.csv(., "data/hist_pot2024.csv", row.names = FALSE)
pot_summary %>% 
  write.csv(., "data/hist_pot.csv", row.names = FALSE)

pot_summary %>% 
    group_by(tech_typ) %>%
    summarise(
        total_gen = sum(quantity, na.rm = TRUE)/1000,
        total_curt = sum(curtailment, na.rm = TRUE)/1000,
        total_pot = sum(potential, na.rm = TRUE)/1000,
        total_cap = sum(capacity, na.rm = TRUE),
        n_hours = sum(n_hours),
        n = n()
    ) %>% 
    janitor::adorn_totals("row") %>%
    mutate(
        cap_factor = total_gen*1000 / (total_cap )/(n_hours/n/2),
        pot_factor = total_pot*1000 / (total_cap )/(n_hours/n/2)
    ) %>% select(-n_hours) %>% 
    kable(
        col.names = c("Type", "Generation (GWh)", "Curtailment", "Potential" ,"Capacity (MW)", "Number of BMUs", "CF","PF"),
        digits = c(0,0,0,0,0,0,2,2),
        # format = "latex",
        format.args = list(big.mark = ",")) %>%
    kable_styling(latex_options = c("scale_down"))
```
```{r}
gen_adj$quantity %>% summary()
gen_adj$curtailment %>% summary()
gen_adj$potential %>% summary()
sum(gen_adj$potential<0)
sum(gen_adj$quantity<0)
(gen_adj$potential/gen_adj$capacity) %>% summary()
```
### Yearly figures

```{r}
ref_catalog_2025 <- fread(
  file.path("data/ref_catalog_wind_2025.csv.gz")) 
# curtailment seasonality
gen_norm <- gen_adj %>% 
  mutate(
    year = year(halfHourEndTime),
    quarter = paste0(year,"Q",quarter(halfHourEndTime))
    ) %>% 
  group_by(
    year,
    bmUnit
  ) %>% 
  arrange(halfHourEndTime) %>%
  mutate(
    quantity = quantity + lag(quantity),
    curtailment = curtailment + lag(curtailment),
    potential = potential + lag(potential)
    ) %>%
  filter(minute(halfHourEndTime) == 0) %>%
  summarise(
    quantity = sum(quantity, na.rm = TRUE),
    curtailment = sum(curtailment, na.rm = TRUE),
    potential = sum(potential, na.rm = TRUE),
    n_hours = n_distinct(halfHourEndTime)
  ) %>% 
  left_join(
    wind.bmus.alt %>% select(elexonBmUnit, bmUnitName, generationCapacity, capacity) %>% unique() ,
    by = c("bmUnit" = "elexonBmUnit") 
  ) %>% 
  filter(
    potential > 0,
    n_hours > max(n_hours)*0.8) %>% 
  left_join(
    ref_catalog_2025 %>% select(bmUnit, tech_typ),
    by = "bmUnit"
  ) %>% 
  mutate(
    cap_factor = quantity / capacity / n_hours,
    curt_factor = curtailment / capacity / n_hours,
    pot_factor = potential / capacity / n_hours,
    short_name = gsub("WF|Wind farm|Windfarm|Offshore","",bmUnitName)
  )

```


### generation
```{r}
# Compute means per year and technology type
means_df_y <- gen_norm %>%
  group_by(year, tech_typ) %>%
  summarise(
    mean_cf = mean(cap_factor, na.rm = TRUE),
    mean_cu = mean(curt_factor, na.rm = TRUE),
    mean_pt = mean(pot_factor, na.rm = TRUE),
     .groups = "drop")

# Identify outliers per year and tech_typ
outliers_df_y <- gen_norm %>%
  group_by(year, tech_typ) %>%
  mutate(
    Q1 = quantile(cap_factor, 0.25, na.rm = TRUE),
    Q3 = quantile(cap_factor, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    is_outlier = cap_factor < (Q1 - 1.5 * IQR) | cap_factor > (Q3 + 1.5 * IQR)
  ) %>%
  filter(is_outlier) %>%
  ungroup()

gen_norm %>% 
  ggplot(aes(x = year, y = cap_factor, group = year, fill = tech_typ))+
  geom_boxplot()+
  facet_wrap(~tech_typ)+
   geom_text(
    data = means_df_y,
    aes(x = year, y = mean_cf, 
    label = paste0("bar(c) == ", sprintf("%.2f", mean_cf))
    ),  
    vjust = -0.7,     # move label slightly above the mean
    size = 2,         # text size
    color = "white",
    parse = TRUE
  ) +
  # outlier labels
  geom_text_repel(
    data = outliers_df_y,
    aes(x = year, y = cap_factor, label = short_name),
    size = 1.5,
    color = "black",
    max.overlaps = 20,     # adjust to allow more/less overlap
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey50"
  ) +
  scale_fill_manual(values = mypalette)+
  theme(legend.position = "none")+
  labs(x = "year", y = "Capacity factor")

ggsave(
    filename = "fig/capacity_factor2.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```

### curtailment year
```{r}
outliers_cu_y <- gen_norm %>%
  group_by(year, tech_typ) %>%
  mutate(
    Q1 = quantile(curt_factor, 0.25, na.rm = TRUE),
    Q3 = quantile(curt_factor, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    is_outlier = curt_factor < (Q1 - 1.5 * IQR) | curt_factor > (Q3 + 1.5 * IQR)
  ) %>%
  filter(is_outlier) %>%
  ungroup()
gen_norm %>% 
  ggplot(aes(x = year, y = curt_factor, group = year, fill = tech_typ))+
  geom_boxplot()+
  facet_wrap(~tech_typ)+
   geom_text(
    data = means_df_y,
    aes(x = year, y = mean_cu, 
    label = paste0("bar(c) == ", sprintf("%.2f", mean_cu))
    ),  
    vjust = -0.7,     # move label slightly above the mean
    size = 2,         # text size
    color = "white",
    parse = TRUE
  ) +
  # outlier labels
  geom_text_repel(
    data = outliers_cu_y,
    aes(x = year, y = curt_factor, label = short_name),
    size = 1.5,
    color = "black",
    max.overlaps = 20,     # adjust to allow more/less overlap
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey50"
  ) +
  scale_fill_manual(values = mypalette)+
  theme(legend.position = "none")+
  labs(x = "year", y = "Capacity factor")

ggsave(
    filename = "fig/curtailment_factor.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```

### potential
```{r}
outliers_pot_y <- gen_norm %>%
  group_by(year, tech_typ) %>%
  mutate(
    Q1 = quantile(pot_factor, 0.25, na.rm = TRUE),
    Q3 = quantile(pot_factor, 0.75, na.rm = TRUE),
    IQR = Q3 - Q1,
    is_outlier = pot_factor < (Q1 - 1.5 * IQR) | cap_factor > (Q3 + 1.5 * IQR)
  ) %>%
  filter(is_outlier) %>%
  ungroup()

gen_norm %>% 
  ggplot(aes(x = year, y = pot_factor, group = year, fill = tech_typ))+
  geom_boxplot()+
  facet_wrap(~tech_typ)+
   geom_text(
    data = means_df_y,
    aes(x = year, y = mean_pt, 
    label = paste0("bar(c) == ", sprintf("%.2f", mean_pt))
    ),  
    vjust = -0.7,     # move label slightly above the mean
    size = 2,         # text size
    color = "white",
    parse = TRUE
  ) +
  # outlier labels
  geom_text_repel(
    data = outliers_df_y,
    aes(x = year, y = pot_factor, label = short_name),
    size = 1.5,
    color = "black",
    max.overlaps = 20,     # adjust to allow more/less overlap
    box.padding = 0.3,
    point.padding = 0.2,
    segment.color = "grey50"
  ) +
  scale_fill_manual(values = mypalette)+
  theme(legend.position = "none")+
  labs(x = "year", y = "Capacity factor")

ggsave(
    filename = "fig/potential_factor.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```
### Quarterly

```{r}
gen_norm_q <- gen_adj %>% 
  mutate(
    year = year(halfHourEndTime),
    quarter = paste0(year,"Q",quarter(halfHourEndTime))
    ) %>% 
  group_by(
    quarter,
    bmUnit
  ) %>% 
  arrange(halfHourEndTime) %>%
  mutate(
    quantity = quantity + lag(quantity),
    curtailment = curtailment + lag(curtailment),
    potential = potential + lag(potential)
    ) %>%
  filter(minute(halfHourEndTime) == 0) %>%
  summarise(
    quantity = sum(quantity, na.rm = TRUE),
    curtailment = sum(curtailment, na.rm = TRUE),
    potential = sum(potential, na.rm = TRUE),
    n_hours = n_distinct(halfHourEndTime)
  ) %>% 
  left_join(
    wind.bmus.alt %>% select(elexonBmUnit, bmUnitName, generationCapacity, capacity) %>% unique() ,
    by = c("bmUnit" = "elexonBmUnit") 
  ) %>% 
  filter(
    potential > 0,
    n_hours > max(n_hours)*0.8) %>% 
  left_join(
    ref_catalog_2025 %>% select(bmUnit, tech_typ),
    by = "bmUnit"
  ) %>% 
  mutate(
    cap_factor = quantity / capacity / n_hours,
    curt_factor = curtailment / capacity / n_hours,
    pot_factor = potential / capacity / n_hours,
    short_name = gsub("WF|Wind farm|Windfarm|Offshore","",bmUnitName)
  )
```
```{r}
gen_norm_q %>% 
  group_by(tech_typ,quarter) %>% 
  summarise(
    across(c(cap_factor,curt_factor,pot_factor), mean)) %>% 
  ggplot(aes(x = quarter, y = cap_factor, group = 1, col = tech_typ))+
  geom_line()+
  facet_wrap(~tech_typ, nrow = 2)+
  scale_color_manual(values = mypalette)+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )+
  labs(x = "Quarter", y = "Capacity factor", col = "")

ggsave(
    filename = "fig/capacity_factor2_q.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)

gen_norm_q %>% 
  group_by(tech_typ,quarter) %>% 
  summarise(
    across(c(cap_factor,curt_factor,pot_factor), mean)) %>% 
  ggplot(aes(x = quarter, y = curt_factor, group = 1, col = tech_typ))+
  geom_line()+
  facet_wrap(~tech_typ, nrow = 2)+
  scale_color_manual(values = mypalette)+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )+
  labs(x = "Quarter", y = "Capacity factor", col = "")
ggsave(
    filename = "fig/curtailment_factor_q.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)

gen_norm_q %>% 
  group_by(tech_typ,quarter) %>% 
  summarise(
    across(c(cap_factor,curt_factor,pot_factor), mean)) %>% 
  ggplot(aes(x = quarter, y = pot_factor, group = 1, col = tech_typ))+
  geom_line()+
  facet_wrap(~tech_typ, nrow = 2)+
  scale_color_manual(values = mypalette)+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, vjust = 0.5)
  )+
  labs(x = "Quarter", y = "Capacity factor", col = "")

ggsave(
    filename = "fig/potential_factor_q.pdf",
    width = 6,
    height = 4,
    units = "in",
    dpi = 300
)
```